workflows:
  android-apk:
    name: RAVE Android APK

    environment:
      node: 22

    scripts:
      - npm install
      - npm run build
      - npx cap sync android
      
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
